version: '3'

services:
  doccer:
    container_name: doccer-example
    build:
      context: .
      args:
        DOCCER_TITLE: Example Doccer Project
        DOCCER_REPOS: https://github.com/wigy/interactive-elements.git
